# Practical Assignment

Practical Assignment

Objective: - Predict Next Sequence
To start with deep learning, the very basic project that you can build is to predict the next digit in a sequence. 

Dataset: - Create a sequence like a list of odd numbers and then build a model and train it to predict the next digit in the sequence. 

Task: - A simple neural network with 2 layers would be sufficient to build the model.

Assignment Submission: - Only submit the Google Colab/Github link.(Make the Link Public).

In [1]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
print(data)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]


In [2]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [3]:
n_steps = 5
X, y = splitSequence(data, n_steps = 5)

In [4]:
print(X)

[[ 10  20  30  40  50]
 [ 20  30  40  50  60]
 [ 30  40  50  60  70]
 [ 40  50  60  70  80]
 [ 50  60  70  80  90]
 [ 60  70  80  90 100]
 [ 70  80  90 100 110]
 [ 80  90 100 110 120]
 [ 90 100 110 120 130]
 [100 110 120 130 140]
 [110 120 130 140 150]
 [120 130 140 150 160]
 [130 140 150 160 170]
 [140 150 160 170 180]
 [150 160 170 180 190]]


In [5]:
print(y)

[ 60  70  80  90 100 110 120 130 140 150 160 170 180 190 200]


In [6]:
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30 40 50] 60
[20 30 40 50 60] 70
[30 40 50 60 70] 80
[40 50 60 70 80] 90
[50 60 70 80 90] 100
[ 60  70  80  90 100] 110
[ 70  80  90 100 110] 120
[ 80  90 100 110 120] 130
[ 90 100 110 120 130] 140
[100 110 120 130 140] 150
[110 120 130 140 150] 160
[120 130 140 150 160] 170
[130 140 150 160 170] 180
[140 150 160 170 180] 190
[150 160 170 180 190] 200


In [7]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[10]
  [20]
  [30]
  [40]
  [50]]

 [[20]
  [30]
  [40]
  [50]
  [60]]]


### Create model

In [8]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

#### Sequential model

In [9]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

View model layers

In [10]:
model.layers

Model summary

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 50)                10400     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


Compile the model

In [12]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

#### Train the model

In [13]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1/1 [==============================] - 3s 3s/step - loss: 19389.8105 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 45ms/step - loss: 16039.9326 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 15ms/step - loss: 10807.1934 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 12ms/step - loss: 3411.6345 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 8ms/step - loss: 1040.3950 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 16ms/step - loss: 271.2613 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 10ms/step - loss: 395.5388 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 14ms/step - loss: 162.1211 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 10ms/step - loss: 147.3361 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 16ms

1/1 [==============================] - 0s 15ms/step - loss: 2.4850 - accuracy: 0.0000e+00
Epoch 79/200
1/1 [==============================] - 0s 14ms/step - loss: 2.3079 - accuracy: 0.0000e+00
Epoch 80/200
1/1 [==============================] - 0s 16ms/step - loss: 3.7792 - accuracy: 0.0000e+00
Epoch 81/200
1/1 [==============================] - 0s 12ms/step - loss: 4.6431 - accuracy: 0.0000e+00
Epoch 82/200
1/1 [==============================] - 0s 11ms/step - loss: 6.3203 - accuracy: 0.0000e+00
Epoch 83/200
1/1 [==============================] - ETA: 0s - loss: 6.4270 - accuracy: 0.0000e+ - 0s 10ms/step - loss: 6.4270 - accuracy: 0.0000e+00
Epoch 84/200
1/1 [==============================] - 0s 12ms/step - loss: 7.1228 - accuracy: 0.0000e+00
Epoch 85/200
1/1 [==============================] - 0s 11ms/step - loss: 6.3289 - accuracy: 0.0000e+00
Epoch 86/200
1/1 [==============================] - 0s 10ms/step - loss: 6.1310 - accuracy: 0.0000e+00
Epoch 87/200
1/1 [======================

1/1 [==============================] - 0s 13ms/step - loss: 0.1143 - accuracy: 0.0000e+00
Epoch 157/200
1/1 [==============================] - 0s 11ms/step - loss: 0.1082 - accuracy: 0.0000e+00
Epoch 158/200
1/1 [==============================] - 0s 10ms/step - loss: 0.1025 - accuracy: 0.0000e+00
Epoch 159/200
1/1 [==============================] - 0s 11ms/step - loss: 0.0965 - accuracy: 0.0000e+00
Epoch 160/200
1/1 [==============================] - 0s 14ms/step - loss: 0.0910 - accuracy: 0.0000e+00
Epoch 161/200
1/1 [==============================] - 0s 16ms/step - loss: 0.0850 - accuracy: 0.0000e+00
Epoch 162/200
1/1 [==============================] - 0s 10ms/step - loss: 0.0797 - accuracy: 0.0000e+00
Epoch 163/200
1/1 [==============================] - 0s 10ms/step - loss: 0.0745 - accuracy: 0.0000e+00
Epoch 164/200
1/1 [==============================] - 0s 13ms/step - loss: 0.0698 - accuracy: 0.0000e+00
Epoch 165/200
1/1 [==============================] - 0s 9ms/step - loss: 0.065

#### Predict

In [14]:
test_data = np.array([90, 100, 110, 120, 230])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 90],
        [100],
        [110],
        [120],
        [230]]])

In [15]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 328ms/step
[[159.64357]]


#### Predict again with different test data

In [16]:
test_data = np.array([160, 170, 180, 190, 300])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[160],
        [170],
        [180],
        [190],
        [300]]])

In [17]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 31ms/step
[[229.78775]]
